name: Prepare Sevdesk


on:
  push:
    branches:
      - development
      - release


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.8.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install & Upgrade
        run: |
          pip3 install -r requirements.txt; pip3 install -r requirements_dev.txt
      - name: Build Sphinx
        run: |
          cd docs; make html
          
      - name: Github Action for curl
        uses: wei/curl@v1.1.1
        with:
          args: https://raw.githubusercontent.com/docarea/cli/master/demo.bash --output upload.bash
      - name: Upload documentation
        run: |
          ls -lah;
          ./upload.bash docs/build/
